### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device  

### ISSUE THREAD

**Issue by Victor-Xiaoyu-Ye** [nv-tlabs/SCube#7]
```
    fvdb_grids = fvdb.gridbatch_from_points(JaggedTensor(cropped_xyz), **grid_batch_kwargs_finest)                                                                                                                                                                                    
RuntimeError: CUDA error: no kernel image is available for execution on the device  
```
I've tried to reinstall and change version of everything.

Many thanks for sharing the info, if u guys have met this before.

**Comment by yifanlu0227** [comment]
Hi, What's your GPU, could you share more information about your environment?

**Comment by Victor-Xiaoyu-Ye** [comment]
80G A800，NVM，Downgrading torch to 2.2.0 solved my problem. closing it.
